### ISSUE TITLE
Build fails with file not found error panic

### ISSUE THREAD

**Issue by CodyD604** [alexforster/libbpf-sys#21]
Trying to compile libbpf-sys 0.4.0-2 on Ubuntu 21.04. Here is a skeleton `Cargo.toml` that illustrates the issue on my system:

```
[package]
name = "foo"
version = "0.1.0"
edition = "2018"

[dependencies]
libbpf-sys = { version = "0.4.0-2" }
```

`cargo build` trace with `RUST_BACKTRACE=1`:
```
   Compiling libbpf-sys v0.4.0-2
error: failed to run custom build command for `libbpf-sys v0.4.0-2`

Caused by:
  process didn't exit successfully: `/tmp/foo/target/debug/build/libbpf-sys-fa6170e7fd760d00/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/cody/.cargo/registry/src/github.com-1ecc6299db9ec823/libbpf-sys-0.4.0-2/build.rs:44:14
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
     1: core::panicking::panic_fmt
               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
     2: core::result::unwrap_failed
               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/result.rs:1355:5
     3: core::result::Result<T,E>::unwrap
               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/result.rs:1037:23
     4: build_script_build::main
               at ./build.rs:34:22
     5: core::ops::function::FnOnce::call_once
               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

`zlib` and `libelf` dependencies on my system:
```
pkg-config --modversion zlib
1.2.11
pkg-config --modversion libelf
0.183
```

Let me know if I can provide any more information that could be used to reproduce. Resolving https://github.com/alexforster/libbpf-sys/issues/20 might give a better picture

**Comment by CodyD604** [comment]
Seems like I was missing `make`. 

`sudo apt install make` seems to have resolved the issue
